### ISSUE TITLE
Is VPS mandatory?

### ISSUE THREAD

**Issue by gopinath6** [devanshbatham/CertEagle#4]
I tried to install this is my windows 10 , python3.8 and executed.Am getitng below error frequently
Is VPS mandatory to run ?

![image](https://user-images.githubusercontent.com/6551119/91645371-1ba95c00-ea62-11ea-97a3-8d931a226d42.png)

**Comment by byhardest** [comment]
I don't think it is mandatory, the VPS is just a suggestion for keeping it running long 24x7x365.

This seems to be some instability on certstream side, I am facing the same today, could any admin confirm?

**Comment by devanshbatham** [comment]
Hello,

The VPS is not mandatory, and yes sometimes the websocket connection breaks (maybe the issue is from certstream time), I will look into it anyways

rgds
Devansh
